### ISSUE TITLE
企业账号加了权限也访问不了Internal RPC Error: RPC Internal Error

### ISSUE THREAD

**Issue by wasd66666** [volcengine/volc-sdk-python#30]
Traceback (most recent call last):
  File "/s_nfs/anaconda3/envs/apollod/lib/python3.8/site-packages/volcengine/visual/VisualService.py", line 233, in high_aes_smart_drawing
    res_json = self.common_json_handler("HighAesSmartDrawing", form)
  File "/s_nfs/anaconda3/envs/apollod/lib/python3.8/site-packages/volcengine/visual/VisualService.py", line 187, in common_json_handler
    raise Exception(str(e))
Exception: b'{"code":50501,"data":{"algorithm_base_resp":{"status_code":100202,"status_message":"do predict failed. err=\'wanx-v1\'"},"binary_data_base64":[]},"message":"Internal RPC Error: RPC Internal Error: do predict failed. err=\'wanx-v1\'. rpc service err_code=100202.","request_id":"20240716172827684E6D405E5B9A04DDE3","status":50501,"time_elapsed":"67.839356ms"}'

**Comment by volc-engine** [comment]
由于该 issue 已存留较长时间，我们将暂时关闭。如果您仍有相关问题：
- 可以重新reopen issue 或者提交 issue
- 或通过[官网工单系统](https://console.volcengine.com/workorder/create)提交支持请求
我们会持续关注并及时响应您的需求。感谢您的理解！
