### ISSUE TITLE
tls消费组消费隔2分钟就会报ConnectionError异常

### ISSUE THREAD

**Issue by Erazx** [volcengine/volc-sdk-python#34]
Python 3.7.4
volcengine 1.0.156

官方示例稍微修改了下

```
...
consumers = []
...

def cleanup(sig, frame):
    for consumer in consumers:
        consumer.stop()

if __name__ == '__main__':
    import signal
    ...
    signal.signal(signal.SIGTERM, cleanup)
    ...
    tls_consumer = TLSConsumer(consumer_config, tls_service, MyLogProcessor())

    consumers.append(tls_consumer)
    # 调用start方法开始持续消费
    tls_consumer.start()

```

运行后隔差不多2分钟就会报异常：

```
Exception in thread Thread-6118:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3-1.25.6-py3.7.egg/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/volcengine/tls/TLSService.py", line 222, in __request
    timeout=self.__timeout)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/volcengine/tls/consumer/log_consumer.py", line 62, in run_with_status
    func()
  File "/usr/local/lib/python3.7/site-packages/volcengine/tls/consumer/log_consumer.py", line 115, in fetch_data
    resp = self.tls_service.consume_logs(req)
  File "/usr/local/lib/python3.7/site-packages/volcengine/tls/TLSService.py", line 398, in consume_logs
    request_headers=api_input[REQUEST_HEADERS])
  File "/usr/local/lib/python3.7/site-packages/volcengine/tls/TLSService.py", line 231, in __request
    raise TLSException(error_code=e.__class__.__name__, error_message=e.__str__())
volcengine.tls.tls_exception.TLSException: Detailed exception information is listed below.
ErrorCode: ConnectionError
ErrorMessage: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/volcengine/tls/consumer/log_consumer.py", line 67, in run_with_status
    elif e.http_code == 429:
AttributeError: 'TLSException' object has no attribute 'http_code'
```

**Comment by volc-sdk-team** [comment]
开发者您好，您反馈的问题涉及API响应异常，建议您通过[官网工单系统](https://console.volcengine.com/workorder/create)提交反馈，我们的技术支持团队将协助您核实并解决问题。

感谢您的理解与支持。
